apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: cluster-mgmt
spec:
  releaseName: ingress-nginx
  chart:
    git: https://github.com/denniszielke/hello_arc.git
    path: charts/ingress-nginx
    ref: master
  values:
    replicaCount: 3